### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by brian6932** [danielgatis/imgcat#12]
```go
❯ imgcat JIF.png
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x341535]

goroutine 1 [running]:
github.com/creack/pty.Getsize(...)
        /home/runner/go/pkg/mod/github.com/creack/pty@v1.1.17/winsize.go:23
main.scale({0xc000088220, 0x1, 0x111e7a})
        /home/runner/work/imgcat/imgcat/main.go:148 +0x75
main.main()
        /home/runner/work/imgcat/imgcat/main.go:277 +0x8f
NativeCommandExitException: Program "imgcat.exe" ended with non-zero exit code: 2.
```
I get this whenever I attempt to open any image file

**Comment by danielgatis** [comment]
I’m going to close this issue because I wasn’t able to reproduce this error in my local environment. If necessary, we can reopen it in the future.
