### ISSUE TITLE
Windows Terminal run error with panic

### ISSUE THREAD

**Issue by hom** [danielgatis/imgcat#17]
I installed `imgcat` with `scoop` and run it to display `avatar.png`	.
`imgcat` throw error with below:
```bash
(base) PS C:\Users\mago\Downloads> imgcat avatar.png
2024/03/19 10:55:42 failed to get the terminal size: unsupported
panic: failed to get the terminal size: unsupported

goroutine 1 [running]:
log.Panicf({0x8cd730, 0xc0000060c0}, {0xc000109f10, 0x18cd63, 0x18cd64})
        /opt/hostedtoolcache/go/1.17.7/x64/src/log/log.go:361 +0x67
main.scale({0xc000064000, 0x1, 0x18cd64})
        /home/runner/work/imgcat/imgcat/main.go:151 +0xe8
main.main()
        /home/runner/work/imgcat/imgcat/main.go:287 +0x15f
```

**Comment by 1kaiser** [comment]
can this kind of introduction be added at the top of `readme.md` [linux | windows | osx] installation `bash -c "$(wget -qO- https://raw.githubusercontent.com/yorukot/superfile/main/install.sh)"` << for example
